version: '3.1'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: .
    command: mix phx.server
    volumes:
      - .:/app
    ports:
     - "4000:4000"
    depends_on:
      - db
